### ISSUE TITLE
Whats "response.time"?

### ISSUE THREAD

**Issue by subversivo58** [song940/node-ntp#2]
I was looking at the example and did not find a "time" property

```javascript
const ntp = require('ntp2');

ntp.time(function(err, response){
  console.log('The network time is :', response.time);
});
```

This property returns `undefined` ever

The object of reponse:

```none
Packet {
  leapIndicator: 0,
  version: 4,
  mode: 4,
  stratum: 2,
  pollInterval: 6,
  precision: 234,
  referenceIdentifier: <Buffer c8 a0 07 ba>,
  referenceTimestamp: 1564518140226.3596,
  originateTimestamp: 0,
  receiveTimestamp: 1564518235902.4453,
  transmitTimestamp: 1564518235902.4573,
  rootDelay: <Buffer 00 00 0a 5f>,
  rootDispersion: <Buffer 00 00 00 d3>,
  destinationTimestamp: 1564518235981,
  d: 1564518235980.988,
  t: 782259117911.9513 }

```

What should i wear?

`response.destinationTimestamp`

**Comment by lsongdev** [comment]
`response.time` just alias to `transmitTimestamp` .

https://github.com/song940/node-ntp/blob/master/index.js#L85

**Comment by subversivo58** [comment]
> `response.time` just alias to `transmitTimestamp` .
> 
> https://github.com/song940/node-ntp/blob/master/index.js#L85

OK but, why can't I get it in the answer?

Whenever I hear this property in the answer, it is **"undefined"**


```javascript
ntp.time(function(err, response){
  console.log('The network time "ntp2" is :', response.destinationTimestamp);
  console.log('The network time "ntp2" is :', response.transmitTimestamp);
  console.log('The network time "ntp2" is :', response.time);
});

// The network time "ntp2" is : 1564540196501
// The network time "ntp2" is : 1564540196376.444
// The network time "ntp2" is : undefined
```


From what I saw on line [52](https://github.com/song940/node-ntp/blob/master/index.js#L52), this property is being added to the message (or not)?


------------------

PS: I am not referring to the property in the NTP function (`NTP.time`), I am referring to the property in the message returned from the Parse function (`NTP.parse`)

Within the parse function, a **time** property should be added to the message as shown on line [85](https://github.com/song940/node-ntp/blob/master/index.js#L85) ... and it is this property that is not returning:

```javascript
ntp.time(function(err, response){
  console.log('Is "time" property in response :', ('time' in response));
});

// Is "time" property in response : false
```

**Comment by lsongdev** [comment]
Maybe my mistake, I publish a newer version to npm and you should upgrade to `ntp2@0.0.2`.

**Comment by subversivo58** [comment]
@song940 , thanks ... I think this closes this question
